name: Generate spec files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3
        
      - name: Clone the google-cloud-go repository
        uses: actions/checkout@v3
        with:
          repository: googleapis/google-cloud-go
          path: google-cloud-go
          fetch-depth: 0

      - name: Generate spec files
        run: |
          pushd google-cloud-go
            ../specmaker.sh
          popd

      - name: Commit and push if it changed
        run: |-
          git config user.name "Major Hayden"
          git config user.email "major@mhtx.net"
          git add specs
          timestamp=$(date -u)
          git commit -m "Updating spec files: ${timestamp}" || exit 0
          git clean -fxd
          git status
          git pull --rebase
          git push